import { Grid } from '@mui/material'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import * as React from 'react';
import Box from '@mui/material/Box';
import Input from '@mui/material/Input';
import InputLabel from '@mui/material/InputLabel';
import InputAdornment from '@mui/material/InputAdornment';
import FormControl from '@mui/material/FormControl';
import AccountCircle from '@mui/icons-material/AccountCircle';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid  >

          <Box sx={{ '& > :not(style)': { m: 1 } }}>

            {/* Primeiro nome   */}
            <FormControl variant="standard">
              <InputLabel htmlFor="input-with-icon-adornment">
                Nome
              </InputLabel>
              <Input
                id="input-with-icon-adornment"
                startAdornment={
                  <InputAdornment position="start">
                    <AccountCircle />
                  </InputAdornment>
                }
              />
            </FormControl>

            <FormControl variant="standard">
              <InputLabel htmlFor="input-with-icon-adornment">
                Sobrenome
              </InputLabel>
              <Input
                id="input-with-icon-adornment"
                startAdornment={
                  <InputAdornment position="start">
                    <AccountCircle />
                  </InputAdornment>
                }
              />
            </FormControl>
          </Box>


          <Box sx={{ '& > :not(style)': { m: 1 } }}>
            <FormControl variant="standard">
              <InputLabel htmlFor="input-with-icon-adornment">
                WhatsApp
              </InputLabel>
              <Input
                id="input-with-icon-adornment"
                startAdornment={
                  <InputAdornment position="start">
                    <AccountCircle />
                  </InputAdornment>
                }
              />
            </FormControl>

            <FormControl variant="standard">
              <InputLabel htmlFor="input-with-icon-adornment">
                Endereço
              </InputLabel>
              <Input
                id="input-with-icon-adornment"
                startAdornment={
                  <InputAdornment position="start">
                    <AccountCircle />
                  </InputAdornment>
                }
              />
            </FormControl>
          </Box>

          <Box sx={{ '& > :not(style)': { m: 1 } }}>
            <FormControl variant="standard">
              <InputLabel htmlFor="input-with-icon-adornment">
                CEP
              </InputLabel>
              <Input
                id="input-with-icon-adornment"
                startAdornment={
                  <InputAdornment position="start">
                    <AccountCircle />
                  </InputAdornment>
                }
              />
            </FormControl>
            <Grid container xs={12} spacing={2}>

              {/* Botão de Salvar */}

              <Stack direction="row" style={{ marginRight: '25px', marginLeft: '80px' }}>
                <Button variant="outlined" style={{ width: '100px' }}>Salvar</Button>
              </Stack>

              {/* Botão de Salvar */}
              <Stack direction="row" style={{ marginRight: '25px' }}>
                <Button variant="outlined" style={{ width: '100px' }}>Editar</Button>
              </Stack>

              {/* Botão de Salvar */}
              <Stack direction="row" style={{ marginRight: '25px' }}>
                <Button variant="outlined" style={{ width: '100px' }}>Atualizar</Button>
              </Stack>
            </Grid>

          </Box>
        </Grid>
      </main>
    </div>
  )
}
